CREATE TABLE IF NOT EXISTS deals (
	ID INT NOT NULL AUTO_INCREMENT,
	URL VARCHAR(1000) NOT NULL,
	IMAGE_URL VARCHAR(1000) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	PRICE DECIMAL(10,2) NOT NULL,
	FEATURED_PRODUCT TINYINT(1) NOT NULL,
	STORE_ID INT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS store (
	ID INT AUTO_INCREMENT,
	STORE_NAME VARCHAR(50) NOT NULL,
	STORE_ICON_PATH VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
);